[package]
name = "custom-theme"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
lazy_static = { workspace = true }
json5 = "1.3.1"
thiserror = "2.0.18"
